# Generated by Django 5.1 on 2024-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.job'),
        ),
    ]
